/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Control.CAdmin;
import Control.CManageUser;
import Model.MyDatabaseConnection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author Sandaru
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        viewProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Lastname = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_Firstname = new javax.swing.JTextField();
        txt_Username = new javax.swing.JTextField();
        txt_Contact = new javax.swing.JTextField();
        txt_ConfirmPassword = new javax.swing.JPasswordField();
        txt_Password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btn_Update = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btn_ManageMeetings = new javax.swing.JButton();
        btn_ManageSignals = new javax.swing.JButton();
        btn_ManageUsers = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Firstname :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, 93, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Profile");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 80, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Lastname :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 149, 93, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Username :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 198, 93, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Contact :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 300, 93, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Password :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 351, 93, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Email :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 248, 93, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Confirm Password :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 157, -1));

        txt_Lastname.setBackground(new java.awt.Color(204, 204, 204));
        txt_Lastname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Lastname.setBorder(null);
        jPanel1.add(txt_Lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 245, -1));

        txt_Email.setBackground(new java.awt.Color(204, 204, 204));
        txt_Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Email.setBorder(null);
        jPanel1.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 245, -1));

        txt_Firstname.setBackground(new java.awt.Color(204, 204, 204));
        txt_Firstname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Firstname.setBorder(null);
        jPanel1.add(txt_Firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 245, -1));

        txt_Username.setBackground(new java.awt.Color(204, 204, 204));
        txt_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Username.setBorder(null);
        jPanel1.add(txt_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 245, -1));

        txt_Contact.setBackground(new java.awt.Color(204, 204, 204));
        txt_Contact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Contact.setBorder(null);
        jPanel1.add(txt_Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 245, -1));

        txt_ConfirmPassword.setBackground(new java.awt.Color(204, 204, 204));
        txt_ConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_ConfirmPassword.setBorder(null);
        txt_ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ConfirmPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 250, -1));

        txt_Password.setBackground(new java.awt.Color(204, 204, 204));
        txt_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Password.setBorder(null);
        txt_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 250, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 240, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 240, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 240, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 240, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 240, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 240, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 240, 10));

        btn_Update.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/kisspng-home-assistant-computer-icons-home-automation-kits-5b2beb86ae54e0.8600300515296049987141 (3).png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 240, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 700));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ManageMeetings.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ManageMeetings.setText("Manage Meetings");
        btn_ManageMeetings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ManageMeetingsActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ManageMeetings, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 187, 351, 45));

        btn_ManageSignals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ManageSignals.setText("Manage Signals");
        btn_ManageSignals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ManageSignalsActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ManageSignals, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 271, 351, 45));

        btn_ManageUsers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ManageUsers.setText("Manage Users");
        btn_ManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ManageUsersActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ManageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 102, 351, 45));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/kisspng-stock-trader-day-trading-analyst-5aba2d669ad811.8506791315221507586342 (1).png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 380, 480));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 540, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ConfirmPasswordActionPerformed

    private void txt_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PasswordActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
     String firstname,lastname,username,email,password,contact,confirmpassword;
String regex = "^[0-9]{10}$";
String Epattern= "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
Pattern pattern = Pattern.compile(Epattern);
firstname = txt_Firstname.getText();
lastname = txt_Lastname.getText();
username = txt_Username.getText();
email = txt_Email.getText();
contact= txt_Contact.getText();
password = txt_Password.getText();
confirmpassword = txt_ConfirmPassword.getText();
Matcher matcher=pattern.matcher(email);
int id =100;
if(firstname.equals(""))
{
JOptionPane.showMessageDialog(null,"First Name Cannot Be Blank!");
}
else if(lastname.equals(""))
{
JOptionPane.showMessageDialog(null,"Last Name Cannot Be Blank!");
}
else if(username.equals(""))
{
JOptionPane.showMessageDialog(null,"Useraname Cannot Be Blank!");
}
else if(email.equals(""))
{
JOptionPane.showMessageDialog(null,"Email Cannot Be Blank!");
}
else if(!matcher.matches())
{
JOptionPane.showMessageDialog(null,"Invaild Email!");
txt_Email.setText("");
}
else if(contact.equals(""))
{
JOptionPane.showMessageDialog(null,"Contact Cannot Be Blank!");
}
else if(!contact.matches(regex))
{
JOptionPane.showMessageDialog(null,"Invalid phone Number!!");
txt_Contact.setText("");
}
else if(password.equals(""))
{
JOptionPane.showMessageDialog(null,"Password Cannot Be Blank!");
}
else if(confirmpassword.equals(""))
{
JOptionPane.showMessageDialog(null,"Confrim Password Cannot Be Blank!");
}
else if(!password.equals(confirmpassword))
{
JOptionPane.showMessageDialog(null,"Password Doesn't match!");
txt_ConfirmPassword.setText("");
}
else{
CAdmin cm=new CAdmin();
    cm.updateAdmin(firstname,lastname,username,email,contact,password,id);

    }
      
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_ManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ManageUsersActionPerformed

        ManageUsers v = new ManageUsers();
        v.setVisible(true);
       this.setVisible(false);


    }//GEN-LAST:event_btn_ManageUsersActionPerformed

    private void btn_ManageSignalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ManageSignalsActionPerformed
        // TODO add your handling code here:
     ManageSignals ms = new ManageSignals();
     this.setVisible(false);
     ms.setVisible(true);
    }//GEN-LAST:event_btn_ManageSignalsActionPerformed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed

        // TODO add your handling code here:
   Home home = new Home();
this.setVisible(false);
home.setVisible(true);
    }//GEN-LAST:event_jLabel9MousePressed

    private void btn_ManageMeetingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ManageMeetingsActionPerformed
        // TODO add your handling code here:
     ManageMeetings manage = new ManageMeetings();
   this.setVisible(false);
     manage.setVisible(true);
    }//GEN-LAST:event_btn_ManageMeetingsActionPerformed
    public void viewProfile()
   { int id=100;
      { ResultSet rs= null;
       try
      {
        MyDatabaseConnection mycon=new MyDatabaseConnection();
        Statement st=mycon.createDbConnection().createStatement();
        rs= st.executeQuery("select * from admins where AdminID='"+id+"'");
        
        if (rs.next())
       {
          
            txt_Firstname.setText(rs.getString("AdminFName"));
            txt_Lastname.setText(rs.getString("AdminLName"));
            txt_Username.setText(rs.getString("AdminUsername"));
            txt_Email.setText(rs.getString("AdminEmail"));
            txt_Contact.setText(rs.getString("AdminContact"));
            txt_Password.setText(rs.getString("AdminPassword"));


        }
        else{
        JOptionPane.showMessageDialog(null,"Invalid username or password");
        }
      }
      catch(Exception ex)
      {JOptionPane.showMessageDialog(null,ex.getMessage());}
    }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ManageMeetings;
    private javax.swing.JButton btn_ManageSignals;
    private javax.swing.JButton btn_ManageUsers;
    private javax.swing.JButton btn_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPasswordField txt_ConfirmPassword;
    private javax.swing.JTextField txt_Contact;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Firstname;
    private javax.swing.JTextField txt_Lastname;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
}
