/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CJournal;
import javax.swing.JTextField;

/**
 *
 * @author Sandaru
 */
public class Journal extends javax.swing.JFrame {
double entry,closed,lotsize,target,stoploss,profit;
String pair,date,zone,type,description,entry1,closed1,lotsize1,target1,stoploss1,profit1,Userid,u="1";
    /**
     * Creates new form Journal
     */
    public Journal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_LotSize = new javax.swing.JTextField();
        date1 = new com.toedter.calendar.JDateChooser();
        cmb_pair = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_BS = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Description = new javax.swing.JTextArea();
        txt_ClosedPrice = new javax.swing.JTextField();
        txt_EntryPrice = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btn_Calculate = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmb_Zone = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txt_StopLoss = new javax.swing.JTextField();
        txt_Target = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txt_Profit = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_LotSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_LotSize.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txt_LotSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 230, -1));

        date1.setForeground(new java.awt.Color(102, 102, 102));
        date1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 210, 30));

        cmb_pair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_pair.setForeground(new java.awt.Color(102, 102, 102));
        cmb_pair.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUR/USD", "AUD/USD", "GBP/USD", "USD/CAD" }));
        getContentPane().add(cmb_pair, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 210, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Pair:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Type:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        cmb_BS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_BS.setForeground(new java.awt.Color(102, 102, 102));
        cmb_BS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buy", "Sell" }));
        getContentPane().add(cmb_BS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 210, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Lot Size:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        txt_Description.setColumns(20);
        txt_Description.setRows(5);
        jScrollPane2.setViewportView(txt_Description);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 270, 80));

        txt_ClosedPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_ClosedPrice.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txt_ClosedPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 230, -1));

        txt_EntryPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_EntryPrice.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txt_EntryPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 230, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 230, 10));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 230, 10));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 230, 10));

        btn_Calculate.setBackground(new java.awt.Color(102, 102, 102));
        btn_Calculate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Calculate.setText("Calculate");
        btn_Calculate.setBorder(null);
        btn_Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 110, 30));

        btn_Clear.setBackground(new java.awt.Color(255, 51, 0));
        btn_Clear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Clear.setText("Cancel");
        btn_Clear.setBorder(null);
        btn_Clear.setPreferredSize(new java.awt.Dimension(80, 30));
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, 100, 30));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        cmb_Zone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_Zone.setForeground(new java.awt.Color(102, 102, 102));
        cmb_Zone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New York", "London", "Asia" }));
        getContentPane().add(cmb_Zone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Zone:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Closed Price");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Entry Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 230, 10));

        txt_StopLoss.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_StopLoss.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txt_StopLoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 230, -1));

        txt_Target.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Target.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txt_Target, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 230, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 230, 10));

        txt_Profit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Profit.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(txt_Profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 230, -1));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 230, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Description:");
        jLabel12.setToolTipText("");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Stop Loss:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Target Price:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Profit/Loss:");
        jLabel15.setToolTipText("");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        btn_Submit.setBackground(new java.awt.Color(51, 153, 255));
        btn_Submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Submit.setText("Submit");
        btn_Submit.setBorder(null);
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, 110, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalculateActionPerformed
       
         entry = Double.parseDouble(txt_EntryPrice.getText());
         closed = Double.parseDouble(txt_ClosedPrice.getText());
         lotsize = Double.parseDouble(txt_LotSize.getText());
         int bs = cmb_BS.getSelectedIndex();
         if(bs == 0){

            profit = ((closed - entry) / lotsize) / 0.1;
            
                txt_Profit.setText(String.valueOf(profit));
         }
        else if(bs == 1){

            profit = ((entry - closed) / lotsize) / 0.1;
                txt_Profit.setText(String.valueOf(profit));
         }
        
    }//GEN-LAST:event_btn_CalculateActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        // TODO add your handling code here:
        User ad = new User();
        this.setVisible(false);
        ad.setVisible(true);
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
        // TODO add your handling code here:
        date = ((JTextField)date1.getDateEditor().getUiComponent()).getText();
        pair = cmb_pair.getSelectedItem().toString();
        zone = cmb_Zone.getSelectedItem().toString();
        type = cmb_BS.getSelectedItem().toString();
        entry1 = txt_EntryPrice.getText();
        lotsize1 = txt_LotSize.getText();
        closed1 = txt_ClosedPrice.getText();
        target1 = txt_Target.getText();
        stoploss1 = txt_StopLoss.getText();
        profit1 = txt_Profit.getText();
        description = txt_Description.getText();
       
        CJournal cj = new CJournal();
        cj.addJournal(date,pair,zone,type,entry1,lotsize1,closed1,target1,stoploss1,profit1,description,u);
        
    }//GEN-LAST:event_btn_SubmitActionPerformed
  public void view(String uid){

    Userid = uid;

  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Journal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Journal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Journal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Journal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Journal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Calculate;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Submit;
    private javax.swing.JComboBox<String> cmb_BS;
    private javax.swing.JComboBox<String> cmb_Zone;
    private javax.swing.JComboBox<String> cmb_pair;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txt_ClosedPrice;
    private javax.swing.JTextArea txt_Description;
    private javax.swing.JTextField txt_EntryPrice;
    private javax.swing.JTextField txt_LotSize;
    private javax.swing.JTextField txt_Profit;
    private javax.swing.JTextField txt_StopLoss;
    private javax.swing.JTextField txt_Target;
    // End of variables declaration//GEN-END:variables
}
