/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.JTextField;
import Control.CSignals;
import net.proteanit.sql.DbUtils;
import Control.*;
import java.sql.*;
/**
 *
 * @author Sandaru
 */
public class ManageSignals extends javax.swing.JFrame {

    /**
     * Creates new form ManageSignals
     */
    public ManageSignals() {
        initComponents();
        viewSignals();
    }
public void viewSignals(){
       ResultSet rs;
      CSignals md = new CSignals();
      rs=md.viewSignals();
      tabel_Signals.setModel(DbUtils.resultSetToTableModel(rs));
          

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_Signals = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        date1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        cmb_BS = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmb_pair = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_EntryPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_StopLoss = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txt_Target = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Description = new javax.swing.JTextArea();
        btn_Submit = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_Signals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Signal ID", "Date", "Pair", "Buy/Sell", "Entry Price", "Stop Loss", "Target Price", "Description"
            }
        ));
        tabel_Signals.setRowHeight(22);
        jScrollPane1.setViewportView(tabel_Signals);
        if (tabel_Signals.getColumnModel().getColumnCount() > 0) {
            tabel_Signals.getColumnModel().getColumn(0).setPreferredWidth(10);
            tabel_Signals.getColumnModel().getColumn(3).setPreferredWidth(10);
            tabel_Signals.getColumnModel().getColumn(4).setPreferredWidth(60);
            tabel_Signals.getColumnModel().getColumn(5).setPreferredWidth(60);
            tabel_Signals.getColumnModel().getColumn(6).setPreferredWidth(60);
            tabel_Signals.getColumnModel().getColumn(7).setPreferredWidth(160);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 280));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("BUY/SELL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 230, 10));

        date1.setForeground(new java.awt.Color(102, 102, 102));
        date1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 210, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Entry Price:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        cmb_BS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_BS.setForeground(new java.awt.Color(102, 102, 102));
        cmb_BS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUY", "SELL", " " }));
        jPanel1.add(cmb_BS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Pair:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        cmb_pair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_pair.setForeground(new java.awt.Color(102, 102, 102));
        cmb_pair.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUR/USD", "AUD/USD", "GBP/USD", "USD/CAD" }));
        jPanel1.add(cmb_pair, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 210, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Date:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        txt_EntryPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_EntryPrice.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txt_EntryPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 230, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Stop Loss:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        txt_StopLoss.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_StopLoss.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txt_StopLoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 230, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 230, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Description:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        txt_Target.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Target.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(txt_Target, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 230, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 230, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Target Price:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        txt_Description.setColumns(20);
        txt_Description.setRows(5);
        jScrollPane2.setViewportView(txt_Description);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 270, 80));

        btn_Submit.setBackground(new java.awt.Color(51, 153, 255));
        btn_Submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Submit.setText("Submit");
        btn_Submit.setBorder(null);
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 110, 30));

        btn_Delete.setBackground(new java.awt.Color(102, 102, 102));
        btn_Delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Delete.setText("Delete");
        btn_Delete.setBorder(null);
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 110, 30));

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
        // TODO add your handling code here:
        String date,pair,bs,entry,stop,target,description;
        date = ((JTextField)date1.getDateEditor().getUiComponent()).getText();
        pair = cmb_pair.getSelectedItem().toString();
        bs = cmb_BS.getSelectedItem().toString();
        entry = txt_EntryPrice.getText();
        stop = txt_StopLoss.getText();
        target = txt_Target.getText();
        description = txt_Description.getText();
       CSignals cs = new CSignals();
       cs.submitSignals(date,pair,bs,entry,stop,target,description);
       viewSignals();
        
       
    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
       
       int row = tabel_Signals.getSelectedRow();
       String cell = tabel_Signals.getModel().getValueAt(row, 0).toString();
       CSignals ce= new CSignals();
       ce.deleteSignals(row,cell);
       refreshTable();
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      Admin ad = new Admin();
      this.setVisible(false);
      ad.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
public void refreshTable(){
ResultSet rs;
      CSignals md = new CSignals();
      rs=md.refreshTable();
      tabel_Signals.setModel(DbUtils.resultSetToTableModel(rs));}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSignals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSignals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSignals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSignals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSignals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Submit;
    private javax.swing.JComboBox<String> cmb_BS;
    private javax.swing.JComboBox<String> cmb_pair;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable tabel_Signals;
    private javax.swing.JTextArea txt_Description;
    private javax.swing.JTextField txt_EntryPrice;
    private javax.swing.JTextField txt_StopLoss;
    private javax.swing.JTextField txt_Target;
    // End of variables declaration//GEN-END:variables
}
